apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/hyperkube-arm:v1.2.0
    command:
    - /hyperkube
    - scheduler
    - --leader-elect=true
    - --master=http://10.0.0.80:8080
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1