apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube-arm:v1.3.6
    command:
    - /hyperkube
    - proxy
    - --master=http://10.0.0.80:8080
    - --proxy-mode=iptables
    securityContext:
      privileged: true